### ISSUE TITLE
Ads Not Showing

### ISSUE THREAD

**Issue by RoninB64** [x0a/uBO-YouTube#1]
Hi, I posted on the Chrome Webstore about this but I'll also post it here since you may see this sooner.
I was unable to get ads to show on desired channels until I refreshed the page. But I found a fix for this by putting your command "*youtube.com/*&disableadblock=1" into the My Filters tab as well as the Whitelist tab in UBlock Origin. But this fix does not work for the Watch Later Playlist. If I add a video to my Watch Later Playlist the ads will not show when the video loads, but if I refresh the page while watching a video in my Watch Later Playlist the ads will show. Could you please fix this?

**Comment by x0a** [comment]
Hi Robin, thanks for your report.

The extension currently doesn't "handle" playlists yet, but it should be easy enough to implement. It seems that the "Watch Later" playlist is on the same URL as any other playlist (youtube.com/playlist) so I'll just add observers for that specific URL and it should be able to handle any playlist.

It should be available as an update within 2-3 days.
