### ISSUE TITLE
Youtube "video" tab becomes broken after most recent update

### ISSUE THREAD

**Issue by autonecromancer** [x0a/uBO-YouTube#16]
Suddenly noticed that (after recent update, nothing much else changed in the system, no new installed add-ons, no new installed ublock lists or changed policies or whatever) youtube "videos" tab under channel is broken.

steps to reproduce:

1) navigate to a channel I am subscribed to and have whitelisted with this add on (works fine)

the address bar will say something like 
https://www.youtube.com/channel/UCJ6KZTTnkE-s2XFJJmoTAkw?igno=re&disableadblock=1

and the channel will display okay.

2) now click videos tab 

the address bar will say 
https://www.youtube.com/user/chilledsanity/videos

and the page will be empty (no content)

console will show 

Uncaught Channel ID not available inject.js:1:15241
    onMutation moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    onMutation self-hosted:935
    (Async: MutationCallback)
    g moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    (Async: promise callback)
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    (Async: promise callback)
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    i moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    <anonymous> moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    <anonymous> moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1

Please help

**Comment by autonecromancer** [comment]
A slightly different error that also spams when this problem arises: 

Uncaught (in promise) TypeError: MutationObserver.observe: Argument 1 is not an object.
    start moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    promise callback*22/< moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    promise callback*22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    i moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    <anonymous> moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    <anonymous> moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
inject.js:1:9971
    start moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    (Async: promise callback)
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    (Async: promise callback)
    22 moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    i moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    <anonymous> moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1
    <anonymous> moz-extension://28613146-c98a-4c61-84f4-df975a4e2900/inject.js:1


**Oh, and my firefox is 79.0 (64-bit)** on linux

**Comment by x0a** [comment]
Thanks for the report. I haven't been able to replicate this bug just yet. Might be linux specific, I'll have to dig a bit deeper. But at first glance, if MutationObserver.observe is being called on an element that doesn't exist yet (i.e. document.body), it could explain the error.

Can you open the error message for the 'MutationObserver.observe' error, click on the first `inject.js:1`

![Capture](https://user-images.githubusercontent.com/13019784/90199816-5d1be500-dd9b-11ea-97fe-0e35634326c2.PNG)

Format code

![Capture2](https://user-images.githubusercontent.com/13019784/90199864-7de43a80-dd9b-11ea-9d99-00a90c5ed6cf.PNG)

And copy/paste the line that's highlighted? (Note the screenshots are an example for the 'Channel ID not detected', but what we really need is the MutationObserver output)

Thanks

**Comment by x0a** [comment]
Hey,

Is this issue still occurring for you?

Thanks
