### ISSUE TITLE
Can't click back on videos

### ISSUE THREAD

**Issue by Jameson5506** [x0a/uBO-YouTube#17]
Extension doesn't let me click back on a video I found via a Google search. Instead it just refreshes the page. Have to right click the back button to return to google or have to click it multiple of times really fast.
See video here: https://streamable.com/3fw9pv
I do not have the NFL YouTube channel included in my whitelist.

Running Windows 10 Pro 10.0.18362 and Firefox 79.0 (64-bit)

**Comment by x0a** [comment]
Thanks for including the video! Really easy to replicate.

I've pushed some changes in v0.10.15 and pushed an update to Mozilla Addons. Try going into Settings > Addons, click on the Options cog, and then click `Check for updates`. Try out the new version and see if this fixes the problem. 

If you see any artifacts/issues as a result of that first page reload, please let me know.
