### ISSUE TITLE
Firefox Sync Integration

### ISSUE THREAD

**Issue by emm88n** [x0a/uBO-YouTube#22]
Whitelist import and export via Firefox Sync would be very much appreciated. Settings synchronization in general with Firefox Sync would be even better.

Thanks for your hard work so far!

**Comment by x0a** [comment]
Thanks for the suggestion!

The extension was already using the `storage.sync` API however it didn't include a mechanism for detecting storage changes made from outside of the extension (i.e. by the browser). I've pushed an update that should fix that and immediately trigger a reload of the settings if changes are detected. Keep in mind that the Firefox Sync interval is currently set to 600 seconds, or about 10 minutes, so you might need to click "Sync Now" in Firefox Sync if you need the changes to appear faster.

The changes are available in 0.13.1 and should be available in Mozilla Addons in a few minutes

Thanks again and feel free to re-open if you notice any issues
