### ISSUE TITLE
Chromium based browser

### ISSUE THREAD

**Issue by Zomblay** [x0a/uBO-YouTube#23]
Hello, I use the browser Iron which is based on Google Chrome. The application doesn't work on it, would it be possible to make it compatible?

**Comment by x0a** [comment]
Hey Zomblay,

Thanks for the report. I just tested this extension on Iron Version 87.0.4450.0 (Official Build) (64-bit) installed through Chrome Web Store and currently can't reproduce the issue. I was able to install it, whitelist certain channels and verify that ads are playing on whitelisted channels, blocked on others. By the way this is with a clean install of SRWare Iron with no extensions other than uBO and uBO-YT. I notice some differences in padding/margin with the 'ADS' button which I'll investigate.

![image](https://user-images.githubusercontent.com/13019784/104118639-2b7a5c00-52f0-11eb-84c2-6ed1253e1186.png)

To clarify, are you having trouble installing or are certain features not working? 

Thanks again

**Comment by Zomblay** [comment]
Thanks for the quick reply,

I was using the Test build (32 bit) of SR Iron before and got the 64 bit version after I saw your comment. The application now works just fine. On the old version, I could install the application but it had no effect no matter what channel whitelisted.

Thanks for your help!
