### ISSUE TITLE
Not allowing any ads to play.

### ISSUE THREAD

**Issue by DShip91** [x0a/uBO-YouTube#26]
Not only does adding "*youtube.com/*&disableadblock=1" to my adblocker's whitelist do nothing at all but even with all of my content blockers disabled the extension doesn't allow any ads to play at all. I've noticed that it _tries_ to load an ad on whitelisted channels (as in the video time changes but nothing else) but the extension doesn't let it happen. What's up with that?

**EDIT:** I'm an idiot. I found a hidden content blocker that I wasn't aware of and got rid of it. Now the add-on is working.

**Comment by x0a** [comment]
Hey don't worry about it. While I wasn't able to reproduce this specific bug, I found some minor unrelated bugs as a result of your bug report. 

Thanks for the report and feel free to open a new issue if anything else occurs!
