### ISSUE TITLE
Feature suggestion: Max ad length toggle

### ISSUE THREAD

**Issue by DShip91** [x0a/uBO-YouTube#29]
There should be a way to set it so that ads above a certain length are automatically blocked.

**Comment by x0a** [comment]
Hey @DShip91 
Apologies for the late reply and thank you for your interest.

This is an existing feature under Settings > Ads > Automatically skip ads, check out your [ad settings](http://youtube.com/ubo-yt#ads) and give it a try. Once you enable it, a dropdown appears where you can currently toggle between 5, 15, 30 seconds. I highly recommend 30 to maximize the odds that your favorite creator will actually receive ad revenue.

Feel free to close the report if this fits your needs however I'm open to suggestions on improving the feature or making it more obvious, so let me know. I've considered showing the dropdown but disabling it until the setting is enabled.

Thanks

**Comment by DShip91** [comment]
Hey there. I think the maximum toggle should be 60 seconds since that gives you enough time to watch two 30-second ads.

**Comment by DShip91** [comment]
Hey there. I think there should be an additional 60-second toggle added to the Automatically skip ads feature.

**Comment by x0a** [comment]
Thank you again for your suggestion! I added a 1m and 2m option, also added some warnings for 5s and 15s letting the user know that those options could deprive channels of revenue.

The changes should be available on Mozilla Addons (Chrome takes a bit longer) in v0.13.10.

Once your extensions are updated, you can try it [here](http://youtube.com/ubo-yt#ads). Feel free to let me know of any bugs/issues
