### ISSUE TITLE
Enable/Disable Ads button dissapeared

### ISSUE THREAD

**Issue by RadioactivePeaches** [x0a/uBO-YouTube#31]
YT updated the UI, making the ads button invisible. Is it possible to add it back? I don't like adding channels manually.

**Comment by x0a** [comment]
Thank you for your report.

I've been trying to reproduce the issue with Firefox/Chrome on Windows/MacOS/Linux and have been unable to. It might be region/browser specific. 

Could you post your current browser/version/operating system so I can test it out?

Thanks

**Comment by RadioactivePeaches** [comment]
Brave browser, Win 10. It allows extension downloads from google store which is how I got it. Everything is up to date at the moment.

**Comment by RadioactivePeaches** [comment]
![Screenshot 2021-06-05 105312](https://user-images.githubusercontent.com/69229439/120879257-57261780-c5ec-11eb-8af7-937d20e5f6ba.png)

**Comment by x0a** [comment]
Thank you for the screenshot!
Looks like a slight redesign (possibly A/B testing), it has not hit my region (US), yet. I'd like to get some hands-on with this version of YouTube.
Are you using YouTube Premium by chance?

**Comment by azalty** [comment]
> Thank you for the screenshot!
> Looks like a slight redesign (possibly A/B testing), it has not hit my region (US), yet. I'd like to get some hands-on with this version of YouTube.
> Are you using YouTube Premium by chance?

Using this addon and YouTube Premium wouldn't make sense since YT Premium removes ads

**Comment by RadioactivePeaches** [comment]
No youtube premium. I live in Thailand if that helps! I didn't turn on any beta modes either. I just looked at my dad's mac and his youtube doesn't seem to have updated... I have no idea

**Comment by x0a** [comment]
Yes you're right. I've been attempting various browser UserAgents/VPN locations and have been unable to get this particular design to load. Since YouTube Premium allows access to newer designs, I may have to bite the bullet here and get it in an effort to fix this particular bug.

Longer term I'll come up with some kind of logging extension to track mutations that users can install to debug issues like these, since YouTube appears to be ramping up site-wide changes.

**Comment by RadioactivePeaches** [comment]
Do you think owning a youtube channel does anything?

**Comment by x0a** [comment]
Possibly. I'm going to go ahead and release the next update and add some logging to see if we can capture some of the modifications that we need to monitor to find the best place to put the ads button/channel ID information.

Also for the record, YouTube premium was a dud, zero access to anything relating to this.

**Comment by adi5166** [comment]
Hi, I also experience this when i had another extension. My extension is for [subtitle](https://chrome.google.com/webstore/detail/youtube-dual-subtitles/hkbdddpiemdeibjoknnofflfgbgnebcm).
It looks like these extensions are in conflict.
