### ISSUE TITLE
Ads button doesn't show on youtube.com/c/ links

### ISSUE THREAD

**Issue by azalty** [x0a/uBO-YouTube#34]
https://www.youtube.com/c/ALT236 :
![image](https://user-images.githubusercontent.com/36737524/124917306-f2e3e280-dff3-11eb-9b88-f2505c5636a4.png)

https://www.youtube.com/channel/UC1KxoDAzbWOWOhw5GbsE-Bw (automatically adds ?igno=re&disableadblock=1) :
![image](https://user-images.githubusercontent.com/36737524/124917593-4ce4a800-dff4-11eb-84cf-c55e1725ec3d.png)
but then, if you use the /channel/ link, you'll be able to click on "videos" and the ads button will still display even though the link is https://www.youtube.com/c/ALT236/videos for example (it's hard to explain so try it)

**Comment by x0a** [comment]
Sorry for the late reply. 

Thanks for the report! Should be a pretty easy fix. An update will be available on Sunday.

Thanks again

**Comment by x0a** [comment]
Fixed this and more in v0.14.0. 

Sorry this took so long. I re-wrote major parts of the underlying code to make it easier to fix bugs. Future issues should be more readily addressable. Support for /user/ channels will be added soon.

Feel free to reply if you encounter any issues.

<hr>
Note: Both Chrome Web Store and Mozilla Addons are posting submission review backlogs of 30 days. Mozilla is usually faster and this extension usually isn't earmarked for review, however there is still a chance of it. 

**Chrome update instructions**

1. Open the Settings menu by clicking **⋮** at the top right
2. Under `More Tools` click on `Extensions`
3. Click on the `Update` button. 

**Firefox update instructions**

1. Open the Settings menu by clicking **≡** at the top right.
2. Click on `Addons`
3. Open the Addons management menu by clicking the **⚙** gear 
4. Click on `Check for updates`. This should update all extensions.
