### ISSUE TITLE
Ads button not working on channel pages when opening the channel from a video

### ISSUE THREAD

**Issue by azalty** [x0a/uBO-YouTube#38]
The ads button still appears, but doesn't do anything when clicked on both /channel/ and /c/ links. This bug only occurs when displaying a channel from a video.

Example:
- Accessing the channel link directly works: https://www.youtube.com/channel/UCDO__Z-tZD4bfG9m4AkK_uA
- Accessing the channel through a video, ex: https://youtu.be/Rm0KsDoy5Uw (then clicking on the channel name) will make the Ads button have no effect. This seems to happen when this is done multiple times (clicking on the channel name then on a video then on the channel name). I'm unable to give a perfect 'how to'.

**Comment by x0a** [comment]
Hey,

Thank you for your bug report. I was able to reproduce the issue. It seems YouTube started delaying adding metadata to the page, choosing to update the DOM first and then add the metadata to `ytd-page-manager`. I pushed an update that favors the DOM over the metadata. It is available on Mozilla Addons now, but will be delayed on Chrome Web Store as usual.

Can you give it a try and see if it fixes the issue?

<hr>

**Chrome update instructions**

1. Open the Settings menu by clicking **⋮** at the top right
2. Under `More Tools` click on `Extensions`
3. Click on the `Update` button. 

**Firefox update instructions**

1. Open the Settings menu by clicking **≡** at the top right.
2. Click on `Addons`
3. Open the Addons management menu by clicking the **⚙** gear 
4. Click on `Check for updates`. This should update all extensions.

**Comment by azalty** [comment]
Thanks a lot! It is working perfectly on firefox :)
