### ISSUE TITLE
Whitelist button not visible anymore on new site layout

### ISSUE THREAD

**Issue by X9VoiD** [x0a/uBO-YouTube#41]
It still shows up when searching for the youtube channel itself
![image](https://user-images.githubusercontent.com/10338031/171018264-c0dd4326-cca5-4975-96eb-b880daf66653.png)

But not when opening any of their videos
![image](https://user-images.githubusercontent.com/10338031/171018393-a818bea0-1a4c-4022-9c1d-bc5b806cf4ad.png)

**Comment by x0a** [comment]
Hey,

Thank you for the report! We received a bug for this exact same issue about a year ago but the new redesign never dropped on this end thus I wasn't able to find the right elements to hook onto. But designs just dropped in my region so it should be a pretty easy fix.

Expect an update within the next 3 days.

Thank you again. I'll let you know once the new release is out.
