### ISSUE TITLE
[ADS] Button Needs to be Updated 

### ISSUE THREAD

**Issue by totallygeekdom** [x0a/uBO-YouTube#45]
YouTube has recently rolled out its redesign. The button needs to be updated to reflect the new design. The green square [ADS] button currently looks out of place next to the white pill shaped Subscribe button.

**Comment by x0a** [comment]
Thanks for the report.

I've already updated the button in Chrome (taking into account edge cases where the old design still appears). Just working on some minor cross-platform issues (button went entirely missing in Firefox, some style differences in Linux). I'm aiming for an update within 24 hours.

Thanks again

**Comment by x0a** [comment]
Fixed in v0.14.10.

Extension is awaiting review by Mozilla/Chrome Web Store. Keep your extensions up to date and let me know if you notice any issues. Keeping issue open for now.
