### ISSUE TITLE
Cookie banner not closing

### ISSUE THREAD

**Issue by BillAdama** [x0a/uBO-YouTube#46]
Hi,
with this extension enabled the cookie banner isn't closing after either accepting or denying all.
If I refresh the page, it does disappear. I tried both with and without the automatic whitelist for subscribed channels.

Thanks,
Luca

**Comment by x0a** [comment]
Apologies for the long wait. It took a while to chase down this bug but I've figured it out now. YouTube was making a request to `/upgrade_visitor_cookie?`, which internal adblocking sent to components in the userscript for parsing. The main component tries to convert that to a URL object which throws an error to YouTube's promise. May seem strange this is the first time this has been caught but apparently youtube has been religious about including the full URL when making fetch requests. E.g. `https://youtube.com/upgrade_visitor_cookie?eom=1`. In any case this is an easy fix, will be out soon.
